kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "example-approver-policy-plugin.labels" $ | indent 4 }}
  name: {{ include "example-approver-policy-plugin.name" $ }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "example-approver-policy-plugin.name" $ }}
subjects:
- kind: ServiceAccount
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
