{{- range .Values.app.rbac.namespaced }}
{{- if not (eq .namespace "") }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "example-approver-policy-plugin.name" $ }}:{{ .apiGroup | replace "." "-" }}-{{ .resource }}
  namespace: {{ .namespace }}
  labels:
{{ include "example-approver-policy-plugin.labels" $ | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "example-approver-policy-plugin.name" $ }}:{{ .apiGroup | replace "." "-" }}-{{ .resource }}
subjects:
- kind: ServiceAccount
  name: {{ include "example-approver-policy-plugin.name" $ }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
---
{{- end }}
